### ISSUE TITLE
Error While Committing Changes: "Generate ID Failed" in generateHeadingIDs.js

### ISSUE THREAD

**Issue by MadDevMax** [reactjs/hi.react.dev#315]
I have translated the "Manipulating the DOM with Refs" page, but when I try to commit my changes, I encounter a "generate ID failed" error.

I have reviewed other pages' PRs to find a solution, but I'm currently stuck. A little help would be greatly appreciated.

Here are the details from the error message:

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
yarn run v1.22.22
$ D:\Work\hi.react.dev\node_modules\.bin\lint-staged
[STARTED] Preparing lint-staged...
[SUCCESS] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] package.json — 2 files
[STARTED] *.{js,ts,jsx,tsx,css} — 0 file
[STARTED] src/**/*.md — 1 file
[SKIPPED] *.{js,ts,jsx,tsx,css} — no files
[STARTED] yarn fix-headings
[FAILED] yarn fix-headings
[FAILED] yarn fix-headings
[SUCCESS] Running tasks for staged files...
[STARTED] Applying modifications from tasks...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[SUCCESS] Reverting to original state because of errors...
[STARTED] Cleaning up temporary files...
[SUCCESS] Cleaning up temporary files...

✖ yarn fix-headings:
D:\Work\hi.react.dev\scripts\headingIDHelpers\generateHeadingIDs.js:28
  const before = match[1] + match[2];
                      ^

TypeError: Cannot read properties of null (reading '1')
    at addHeaderID (D:\Work\hi.react.dev\scripts\headingIDHelpers\generateHeadingIDs.js:28:23)
    at D:\Work\hi.react.dev\scripts\headingIDHelpers\generateHeadingIDs.js:79:18
    at Array.forEach (<anonymous>)
    at addHeaderIDs (D:\Work\hi.react.dev\scripts\headingIDHelpers\generateHeadingIDs.js:67:9)
    at D:\Work\hi.react.dev\scripts\headingIDHelpers\generateHeadingIDs.js:105:26
    at Array.forEach (<anonymous>)
    at main (D:\Work\hi.react.dev\scripts\headingIDHelpers\generateHeadingIDs.js:98:9)

Node.js v22.2.0
error Command failed with exit code 1.
$ node scripts/headingIdLinter.js --fix D:/Work/hi.react.dev/src/content/learn/manipulating-the-dom-with-refs.md
Note: heading ### उदाहरण: टेक्स्ट इनपुट पर फोकस करना has a different ID (example-focusing-a-text-input) than what GH generates for it: उदाहरण-टेक्स्ट-इनपुट-पर-फोकस-करना:
Note: heading ### उदाहरण: किसी एलिमेंट पर स्क्रॉल करना has a different ID (example-scrolling-to-an-element) than what GH generates for it: उदाहरण-किसी-एलिमेंट-पर-स्क्रॉल-करना:
Note: heading #### लिस्ट के रेफ्स को मैनेज करने के लिए रेफ कॉलबैक का उपयोग करना has a different ID (how-to-manage-a-list-of-refs-using-a-ref-callback) than what GH generates for it: लिस्ट-के-रेफ्स-को-मैनेज-करने-के-लिए-रेफ-कॉलबैक-का-उपयोग-करना:
Note: heading ## किसी अन्य कंपोनेंट के DOM नोड्स को एक्सेस करना has a different ID (accessing-another-components-dom-nodes) than what GH generates for it: किसी-अन्य-कंपोनेंट-के-dom-नोड्स-को-एक्सेस-करना:
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky - pre-commit hook exited with code 1 (error)
```

**Steps Taken:**
- I have checked the PRs of other pages and tried to find solutions, but I am still stuck.

**Request:**
- Any help or suggestions would be greatly appreciated!

**Comment by arshadkazmi42** [comment]
Seeing the error logs it looks like there is some issue with the headings. Cross check the headings with the English version. 

The headings should use correct number of `#` as there in English. Any mismatch in that will break the build.

> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -

Is this the commit command you are using? Any specific reason for using this and not doing a simple commit with `git commit -m "your commit message"` ?

**Comment by MadDevMax** [comment]
Getting the same result with a simple commit message as you suggested.
however
The heading in Hindi (### उदाहरण: टेक्स्ट इनपुट पर फोकस करना) results in an auto-generated id by GitHub as:
उदाहरण-टेक्स्ट-इनपुट-पर-फोकस-करना
However, documentation has the ID manually set as:
example-focusing-a-text-input

Is it intended behaviour or its a bug?

**Comment by arshadkazmi42** [comment]
Your heading should look like this after translation

```
### उदाहरण: टेक्स्ट इनपुट पर फोकस करना {/*example-focusing-a-text-input*/}
```

you should not translate `{/*example-focusing-a-text-input*/}` this part and keep it as is. As that is used for links and we do not want to change that.

**Comment by MadDevMax** [comment]
I haven't changed that.it is the same as you mentioned.

**Comment by arshadkazmi42** [comment]
In that case, I will suggest you to create a PR using Github web UI. Just edit the file [here](https://github.com/reactjs/hi.react.dev/blob/main/src/content/learn/manipulating-the-dom-with-refs.md) and paste your translation changes.

Then you will be able to create a PR from the web ui itself. Once the PR is ready, I will be able check the changes and debug further.

**Comment by MadDevMax** [comment]
Its worked directly from UI thanks for the help @arshadkazmi42 .
